---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-ski
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: prod-ski
type: Opaque
data:
  POSTGRES_DB: mydb
  POSTGRES_USER: root
  POSTGRES_PASSWORD: "4118"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: prod-ski
type: Opaque
data:
  PORT: "8080"
  DATABASE: "postgres://root:4118@postgres:5432/mydb?sslmode=disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: prod-ski
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: prod-ski
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: api
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: PORT
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DATABASE
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
  namespace: prod-ski
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: api-cluster-ip-service
  namespace: prod-ski
spec:
  type: LoadBalancer
  selector:
    component: api
  ports:
    - port: 8080
      targetPort: 8080
