export default () => ({
  database_url: process.env.DATABASE_URL,
  DOCKER_INFLUXDB_INIT_USERNAME: process.env.DOCKER_INFLUXDB_INIT_USERNAME,
  DOCKER_INFLUXDB_INIT_PASSWORD: process.env.DOCKER_INFLUXDB_INIT_PASSWORD,
  DOCKER_INFLUXDB_INIT_ORG: process.env.DOCKER_INFLUXDB_INIT_ORG,
  DOCKER_INFLUXDB_INIT_BUCKET: process.env.DOCKER_INFLUXDB_INIT_BUCKET,
});
